cassandra:
  hostname: cassandra
  image: cassandra:latest
  command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
  ports:
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
hadoop:
  hostname: hadoop
  image: ubuntu:16.04
  ports:
    - "54310:54310"
    - "54311:54311"
