---
- hosts: bigd_test
  remote_user: ubuntu
  vars:
    home: /home/ubuntu
  tasks:
  - name: Deploy files from GitHub
    git:
      repo: "ssh://git@github.com/CUBigDataClass/DisasterAnalytics"
      dest: "{{ home }}/app"
      key_file: "{{ home }}/.ssh/da_deploy"
      accept_hostkey: yes
      force: yes
      version: release
  - name: Start website.py
    shell: "cd {{home}}/app; nohup python3 website.py &"
    poll: 0
